---
title: "Riparias - Baseline"
author: "Sander Devisscher"
date: "`r Sys.time()`"
output: html_document
---

```{r libraries, include=FALSE}
library(sf)
library(sp)
library(raster)
library(leaflet)
library(tidyverse)
library(knitr)
library(rgbif)
library(dplyr)

crs_wgs <- CRS("+proj=longlat +datum=WGS84 +no_defs")
```

```{r}
#upload species keys from Riparias checklist
riparias_checklist <- rgbif::name_usage(
  datasetKey = "fd004d9a-2ea4-4244-bb60-0df508d20a15", 
)

gbif_backbone_keys <- 
  riparias_checklist$data %>%
  dplyr::filter(origin == "SOURCE") %>%
  pull(.data$nubKey)

gbif_backbone_keys
```
```{r}
#download occurences from species from GBIF

#add username, email and password of GBIF account to R.environ en herstart Rstudio
#install.packages("usethis")
#usethis::edit_r_environ()


gbif_download <- occ_download(
  pred_in("taxonKey", gbif_backbone_keys),
  pred_in("country", c("BE")),
  pred("hasCoordinate", TRUE),
  pred_gte("year", 2000)
  )                              

#occ_download_get(key= "")
occ_download_wait(gbif_download)

write.csv(as.character(occ_download_meta(gbif_download)),
          paste0("gbif_download", Sys.Date(), ".csv"))

a <- occ_download_get(gbif_download, overwrite=TRUE)%>%
  occ_download_import()%>%
  filter(!is.na(decimalLongitude), !is.na(decimalLatitude)) 
```

```{r get perimeter shape, include = FALSE}
perimeter_shape <- st_read("~/Github/riparias-prep/data/spatial/Riparias_subunits/RBU_RIPARIAS_12_02_2021.geojson")
```

```{r test perimeter, eval = FALSE}
leaflet() %>% 
  addTiles() %>% 
  addPolylines(data=perimeter_shape, color="red")
```


```{r}
pointdata <-  st_as_sf(a,
               coords = c("decimalLongitude",
                          "decimalLatitude"),
               crs = 4326)
```



https://docs.google.com/spreadsheets/d/15f17hXE9ZyUxEe2xA0seKs0CSibgYJdkaWcnmVoI1yY/edit#gid=0


```{r intersect with perimeter, include = FALSE}
points_in_perimeter <- st_intersection(pointdata, perimeter_shape)

points_in_perimeter_sel <- points_in_perimeter %>%
  dplyr::select(species,
                occurrenceStatus,
                identificationVerificationStatus,
                speciesKey,
                taxonKey,
                individualCount,
                vernacularName,
                collectionCode,
                references,
                year,
                kingdomKey)

points_in_perimeter_sel<- points_in_perimeter_sel%>%
  filter(!identificationVerificationStatus %in% c('unverified','not validated'))
  
st_write(points_in_perimeter_sel,  "~/GitHub/riparias-prep/data/spatial/baseline/points_in_perimeter_sel.geojson")
```

```{r test points, eval = FALSE}
leaflet(points_in_perimeter) %>% 
  addTiles() %>% 
  addCircleMarkers()
```

```{r export baseline shapes}
baseline_state_plants <- points_in_perimeter_sel %>%
    filter(kingdomKey==6)%>%
    filter(year<2021)%>%
    filter(occurrenceStatus!='ABSENT')

baseline_state_animals <- points_in_perimeter_sel%>%
    filter(kingdomKey==1)%>%
    filter(year<2016)%>%
    filter(occurrenceStatus!='ABSENT')

baseline_state <- rbind(baseline_state_animals,
                       baseline_state_plants)


st_write(baseline_state,  "~/GitHub/riparias-prep/data/spatial/baseline/baseline.geojson")

```
```{r export update shapes}
current_state_plants <- points_in_perimeter_sel %>%
    filter(kingdomKey==6)%>%
    filter(year>=2021)%>%
    filter(occurrenceStatus!='ABSENT')

current_state_animals <- points_in_perimeter_sel%>%
    filter(kingdomKey==1)%>%
    filter(year>=2016)%>%
    filter(occurrenceStatus!='ABSENT')

current_state <- rbind(current_state_animals,
                       current_state_plants)

st_write(current_state,  "~/GitHub/riparias-prep/data/spatial/baseline/current_state.geojson")
```




