---
title: "Riparias - Baseline"
author: "Sander Devisscher"
date: "`r Sys.time()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r libraries, include=FALSE}
library(sf)
library(sp)
library(raster)
library(leaflet)
library(tidyverse)
library(knitr)
library(rgbif)
library(dplyr)

crs_wgs <- CRS("+proj=longlat +datum=WGS84 +no_defs")
```

```{r}
#upload species keys from Riparias checklist
riparias_checklist <- rgbif::name_usage(
  datasetKey = "fd004d9a-2ea4-4244-bb60-0df508d20a15", 
)

gbif_backbone_keys <- 
  riparias_checklist$data %>%
  dplyr::filter(origin == "SOURCE") %>%
  pull(.data$nubKey)

gbif_backbone_keys
```
```{r}
#download occurences from species from GBIF

#add username, email and password of GBIF account to R.environ en herstart Rstudio
#install.packages("usethis")
#usethis::edit_r_environ()


gbif_download <- occ_download(
  pred_in("taxonKey", gbif_backbone_keys),
  pred_in("country", c("BE")),
  pred("hasCoordinate", TRUE),
  pred_gte("year", 2000)
  )                              

#occ_download_get(key= "")
occ_download_wait(gbif_download)

a <- occ_download_get(gbif_download, overwrite=TRUE) %>%
  occ_download_import()%>%
  filter(!is.na(decimalLongitude), !is.na(decimalLatitude))
```

```{r get perimeter shape, include = FALSE}
perimeter_shape <- st_read("https://raw.githubusercontent.com/inbo/riparias-prep/master/data/spatial/perimeter/Riparias_Official_StudyArea.geojson")
```

```{r test perimeter, eval = FALSE}
leaflet(perimeter_shape) %>% 
  addTiles() %>% 
  addPolylines()
```

```{r get pointdata, include = FALSE}

```
```{r}
pointdata <-  st_as_sf(a,
               coords = c("decimalLongitude",
                          "decimalLatitude"),
               crs = 4326)
```

```{r test points, eval = FALSE}
leaflet(points_in_perimeter) %>% 
  addTiles() %>% 
  addCircleMarkers()
```

https://docs.google.com/spreadsheets/d/15f17hXE9ZyUxEe2xA0seKs0CSibgYJdkaWcnmVoI1yY/edit#gid=0


```{r intersect with perimeter, include = FALSE}
points_in_perimeter <- st_intersection(pointdata, perimeter_shape)%>%
  select(BEKNAAM, species,occurrenceStatus, speciesKey, taxonKey,     individualCount,vernacularName, collectionCode, references, year)

st_write(points_in_perimeter,  "points_in_perimeter.geojson")
```

```{r export baseline shapes}
baseline <- points_in_perimeter %>% filter(year>=2000 & year<=2015)

st_write(baseline,  "baseline.geojson")

```

```{r export update shapes}
current_state <- points_in_perimeter %>% filter(year>2015)

st_write(current_state,  "current_state.geojson")
```




