---
title: "cm_bul_bul"
author: "Sander Devisscher"
date: "9-9-2021"
output: html_document
---

prior to running this script you might want to download any of these zipfiles:
only p_jocosus @ https://www.gbif.org/occurrence/download/0286357-200613084148143 or
both @ https://www.gbif.org/occurrence/download/0013307-210819072339941 
and place the zipfile into the "./data/raw/bul_bul_downloads/" - folder

```{r libraries, include=FALSE}
library(devtools)
install_github("trias-project/trias", ref = "73_climate_matching_function", force = TRUE)
library(leaflet)
library(tidyverse)
library(trias)
```

```{r taxonkeys, include=FALSE}
p_jocosus <- 2486151
p_cafer <- 2486131

taxonkeys <- c(p_jocosus, p_cafer)
```

```{r cm, include=FALSE}
zipfile <- "./data/raw/bul_bul_downloads/occurrence_subset.zip"

gc(reset = TRUE)
if(memory.limit() <= 80000){
  memory.limit(size = as.numeric(80000))
}

if(file.exists(zipfile)){
  output2 <- climate_match(region = "Europe",
                        taxonkey = taxonkeys,
                        BasisOfRecord = c("HUMAN_OBSERVATION", "PRESERVED_SPECIMEN", "UNKNOWN"),
                        zipfile = zipfile,
                        maps = TRUE)
}else{
  output2 <- climate_match(region = "Europe",
                        taxonkey = taxonkeys,
                        BasisOfRecord = c("HUMAN_OBSERVATION", "PRESERVED_SPECIMEN", "UNKNOWN"),
                        maps = TRUE)
}
```

Kaarten: 
per soort
1. Current global
2. Current Europe
3. Future Europe

```{r species_maps}
output <- output2

#Worldwide
p_jocosus_map_world <- output$single_species_maps$`2486151` %>% 
  leaflet::setView(lat = 0, lng = 0, zoom = 2)

p_cafer_map_world <- output$single_species_maps$`2486131` %>% 
  leaflet::setView(lat = 0, lng = 0, zoom = 2)

#Europe
zoomlevel <- 3.5

p_jocosus_map_europe <- output$single_species_maps$`2486151` %>% 
  leaflet::setView(lat = 51, lng = 15, zoom = zoomlevel)

p_cafer_map_europe <- output$single_species_maps$`2486131` %>% 
  leaflet::setView(lat = 51, lng = 15, zoom = zoomlevel)
```

```{r data}
europe_cm <- output$cm

europe_cm_old <- output_backup$cm 

europe_cm_combined <- europe_cm %>% 
  left_join(europe_cm_old, by = c("Classification", "scenario")) %>% 
  mutate(perc_climate_diff = round((perc_climate.x - perc_climate.y)*100,2))

write_csv(europe_cm, "./bul_bul/europe_cm_corrected.csv")
```

