```{r prep packages}
library(tidyverse)
library(rgbif)
library(sf)
```

```{r prep memory}
rm(list = ls())
```

```{r GBIF download}
# "https://www.gbif.org/dataset/fd004d9a-2ea4-4244-bb60-0df508d20a15"
# cf. voor nubKey

# [1] 13 soorten die in het "alert list"-rapport zijn beschreven EN/OF bestreden zijn onder C2

rip <- name_usage(datasetKey = "fd004d9a-2ea4-4244-bb60-0df508d20a15")$data %>%
  subset(rank != "KINGDOM") %>%
  filter(species %in% c("Aponogeton distachyos", # [1]
                        "Crassula helmsii",
                        "Egeria densa",
                        "Erythranthe guttata",
                        "Houttuynia cordata",
                        "Koenigia polystachya",
                        "Lagarosiphon major",
                        "Ludwigia peploides",
                        "Lysichiton americanus",
                        "Petasites japonicus",
                        "Pontederia cordata",
                        "Saururus cernuus",
                        "Zizania latifolia"
                        )
         )
``` 

```{r make new GBIF dataset}
# gbif_download <- occ_download(
#   user = "bram_dhondt",
#   email = "", # complete
#   pwd = "", # complete
#   pred_in("taxonKey", rip$nubKey),
#   pred("hasCoordinate", TRUE),
#   pred_in("country", c("BE")),     # Include other countries in vector, if desired
#   pred_gte("year", 2021))          # Include earlier year, if desired

# Result as of 2026-05-05 :
# key = "0009927-260430073515954" (also see the URL of the DOI)
# DOI = 10.15468/dl.kybcxg
```

```{r}
# GBIFdata <- occ_download_get(key = "0009927-260430073515954",
#                              path = "./data/interim/adhoc_2026-05_base-stats/",
#                              overwrite = TRUE)
```

```{r}
data.raw <- occ_download_import(key = "0009927-260430073515954",
                                path = "./data/interim/adhoc_2026-05_base-stats/")
```

```{r}
data <- data.raw %>%
  distinct(occurrenceID, .keep_all = TRUE) %>% # get rid of duplicates
  filter(!is.na(decimalLongitude), !is.na(decimalLatitude)) %>% # with coordinates
  filter(occurrenceStatus != 'ABSENT') %>%  # filter out absence data
  # take what you need
  select(gbifID,
         # datasetID, datasetName,
         # eventDate,
         year,
         species,
         decimalLatitude, decimalLongitude,
         identificationVerificationStatus) %>%
  # make spatial
  st_as_sf(coords = c("decimalLongitude", "decimalLatitude"),
           crs = "+proj=longlat +datum=WGS84")
```

```{r}
grid <- read_sf("./data/spatial/Riparias_subunits/EEA_1km_Riparias.geojson")
```

```{r overlay}
data <- st_transform(data, crs = st_crs(grid))

grid.data <- st_join(grid, data) %>%
  filter(!is.na(species))
```

```{r check data}
ggplot() +
  geom_sf(data = grid) +
  geom_sf(data = subset(grid.data,
                        species == "Zizania latifolia" & year == 2024),
                        fill = "red") +
  theme_bw()
```

```{r summaries}
# aantal hokken per jaar
summ1 <- grid.data %>% 
  group_by(year) %>% 
  summarize(nr_cells = n_distinct(CELLCODE))

# aantal hokken per soort & jaar
summ2 <- grid.data %>% 
  group_by(year, species) %>% 
  summarize(nr_cells = n_distinct(CELLCODE)) %>% 
  arrange(species, year)

# aantal hokken per soort
summ3 <- grid.data %>% 
  group_by(species) %>% 
  summarize(nr_cells = n_distinct(CELLCODE))
# de som van nr_cells = # POPULATIES (soort x hok combinaties)
sum(summ3$nr_cells)
```

```{r}
ggplot() +
  geom_line(data = summ.year, aes(x = year, y = nr_cells, color = species))
```

# NEW CELLCODES (all species)

Analyse van het aantal hokken dat jaarlijks nieuw was, i.e. dat nog in geen enkele van de voorgaande jaren was vastgesteld.

```{r}
  spdata <- grid.data %>% 
  filter(year < 2026) %>% 
  st_drop_geometry()
  
  spdata.21 <- spdata %>% filter(year == 2021) %>% select(CELLCODE) %>% distinct()
  spdata.22 <- spdata %>% filter(year == 2022) %>% select(CELLCODE) %>% distinct()
  spdata.23 <- spdata %>% filter(year == 2023) %>% select(CELLCODE) %>% distinct()
  spdata.24 <- spdata %>% filter(year == 2024) %>% select(CELLCODE) %>% distinct()
  spdata.25 <- spdata %>% filter(year == 2025) %>% select(CELLCODE) %>% distinct()
  
  spdata.new.21 <- spdata.21
  spdata.new.22 <- anti_join(spdata.22, rbind(spdata.21))
  spdata.new.23 <- anti_join(spdata.23, rbind(spdata.new.21,
                                            spdata.new.22))
  spdata.new.24 <- anti_join(spdata.24, rbind(spdata.new.21,
                                            spdata.new.22,
                                            spdata.new.23))
  spdata.new.25 <- anti_join(spdata.25, rbind(spdata.new.21,
                                            spdata.new.22,
                                            spdata.new.23,
                                            spdata.new.24))
  cells <- spdata %>%
    group_by(year) %>%
    summarize(nr_cells = n_distinct(CELLCODE)) %>%
    arrange(year)
  
  cells$new <- rbind(nrow(spdata.new.21),
                     nrow(spdata.new.22),
                     nrow(spdata.new.23),
                     nrow(spdata.new.24),
                     nrow(spdata.new.25))
```

Check : n_distinct(spdata$CELLCODE) moet gelijk zijn aan sum(cells$new)

```{r}
ggplot(data = cells, aes(x = year)) +
  geom_col(aes(y = new), color = "grey", fill = "grey") +
  geom_line(aes(y = nr_cells), color = "red") +
  geom_point(aes(y = nr_cells), color = "red", size = 3) +
  ggtitle("all species", "line = all locations, bars = new locations") +
  labs(x = NULL, y = NULL) +
  theme_bw()
```

```{r}
ggsave(paste0("./data/output/newpops_", "all-species", "_", Sys.Date(), ".png"))
```

# NEW CELLCODEs (per species)

## FUNCTION (for those with full data)

```{r}
new_cells_analysis <- function(SPECIES) {

  spdata <- grid.data %>% 
  filter(species == SPECIES,
         year < 2026) %>% 
  st_drop_geometry()
  
  spdata.21 <- spdata %>% filter(year == 2021) %>% select(CELLCODE) %>% distinct()
  spdata.22 <- spdata %>% filter(year == 2022) %>% select(CELLCODE) %>% distinct()
  spdata.23 <- spdata %>% filter(year == 2023) %>% select(CELLCODE) %>% distinct()
  spdata.24 <- spdata %>% filter(year == 2024) %>% select(CELLCODE) %>% distinct()
  spdata.25 <- spdata %>% filter(year == 2025) %>% select(CELLCODE) %>% distinct()
  
  spdata.new.21 <- spdata.21
  spdata.new.22 <- anti_join(spdata.22, rbind(spdata.21))
  spdata.new.23 <- anti_join(spdata.23, rbind(spdata.new.21,
                                            spdata.new.22))
  spdata.new.24 <- anti_join(spdata.24, rbind(spdata.new.21,
                                            spdata.new.22,
                                            spdata.new.23))
  spdata.new.25 <- anti_join(spdata.25, rbind(spdata.new.21,
                                            spdata.new.22,
                                            spdata.new.23,
                                            spdata.new.24))
  cells <- spdata %>%
    group_by(year) %>%
    summarize(nr_cells = n_distinct(CELLCODE)) %>%
    arrange(year)
  
  cells$new <- rbind(nrow(spdata.new.21),
                     nrow(spdata.new.22),
                     nrow(spdata.new.23),
                     nrow(spdata.new.24),
                     nrow(spdata.new.25))
  return(cells)
}
```

```{r}
complete.species <- data.frame(name = c("Crassula helmsii",
                                        "Houttuynia cordata",
                                        "Lysichiton americanus",
                                        "Petasites japonicus",
                                        "Zizania latifolia")
                               )

for (NAME in complete.species$name) {
  
  print(NAME)
  
  NCA <- new_cells_analysis(NAME)
  
  plot <- ggplot(data = NCA, aes(x = year)) +
    geom_col(aes(y = new), color = "grey", fill = "grey") +
    geom_line(aes(y = nr_cells), color = "red") +
    geom_point(aes(y = nr_cells), color = "red", size = 3) +
    ggtitle(NAME, "line = all locations, bars = new locations") +
    labs(x = NULL, y = NULL) +
    theme_bw()
  
  print(plot)
  
  ggsave(paste0("./data/output/newpops_", NAME, "_", Sys.Date(), ".png"))

}
```